import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/tokens/index.ts',
    'src/theme/index.ts',
    'src/types/index.ts',
    'src/domain/index.ts',
    'src/brand/index.ts',
    'src/components/index.ts',
    'src/org/index.ts',
  ],
  format: ['esm'],
  dts: true,
  clean: true,
  treeshake: true,
  external: ['react', 'react-dom', 'antd', 'iconoir-react'],
  // tokens.css is generated by build-tokens.ts (prebuild); ship it as a side-effect entry.
  onSuccess: 'cp src/tokens/tokens.css dist/tokens.css',
});
