/* GENERATED by scripts/build-tokens.ts from src/tokens/tokens.json — do not edit. */

export type OKLCH = readonly [number, number, number]; // [L 0..1, C, H°]

/** Format OKLCH components as a CSS `oklch()` string. */
export const oklch = ([l, c, h]: OKLCH, a = 1): string =>
  `oklch(${(l * 100).toFixed(1)}% ${c.toFixed(3)} ${h.toFixed(1)}${a === 1 ? '' : ` / ${a}`})`;

/** Nudge perceptual lightness, clamped to [0,1] — derive hover/active/soft states on one hue. */
export const L = ([l, c, h]: OKLCH, d: number): OKLCH => [Math.min(1, Math.max(0, l + d)), c, h];

/** Authoritative OKLCH components — store as [L,C,H] so CI can re-check contrast + gamut. */
export const roleOklch = {
  light: { primary: [0.549, 0.134, 40.1], onPrimary: [1, 0, 0], primaryHover: [0.502, 0.122, 39.9], primaryActive: [0.456, 0.109, 40.5], link: [0.471, 0.112, 39.4], primarySoft: [0.923, 0.029, 54], primaryWash: [0.965, 0.015, 54.9], text: [0.247, 0.016, 53.8], textSecondary: [0.496, 0.022, 67.3], textTertiary: [0.533, 0.035, 81.6], bgLayout: [0.95, 0.014, 84.6], bgContainer: [0.988, 0.008, 91.5], bgElevated: [0.962, 0.014, 84.6], bgSunken: [0.915, 0.022, 83.3], border: [0.9, 0.023, 84.6], borderSecondary: [0.933, 0.02, 84.6], focus: [0.471, 0.112, 39.4] },
  dark: { primary: [0.745, 0.12, 47.4], onPrimary: [0.226, 0.035, 37.5], primaryHover: [0.714, 0.122, 48.2], primaryActive: [0.673, 0.12, 48.8], link: [0.765, 0.114, 48.1], primarySoft: [0.277, 0.033, 46.2], primaryWash: [0.233, 0.027, 50.7], text: [0.929, 0.018, 73.1], textSecondary: [0.727, 0.024, 74], textTertiary: [0.621, 0.025, 78.1], bgLayout: [0.201, 0.01, 52.9], bgContainer: [0.229, 0.015, 57.5], bgElevated: [0.214, 0.014, 61.8], bgSunken: [0.168, 0.009, 59], border: [0.323, 0.017, 63.4], borderSecondary: [0.273, 0.014, 67.2], focus: [0.765, 0.114, 48.1] },
} as const;

export const yarnOklch = {
  light: { brick: [0.549, 0.134, 40.1], teal: [0.515, 0.064, 232.1], ochre: [0.705, 0.121, 80.3], fern: [0.59, 0.093, 139.9], clay: [0.609, 0.123, 38], plum: [0.517, 0.077, 316.6] },
  dark: { brick: [0.745, 0.12, 47.4], teal: [0.728, 0.057, 220.1], ochre: [0.792, 0.118, 82.9], fern: [0.72, 0.078, 135.6], clay: [0.709, 0.105, 39.6], plum: [0.709, 0.072, 315.8] },
} as const;

export const semanticOklch = {
  light: { success: [0.59, 0.093, 139.9], warning: [0.705, 0.121, 80.3], danger: [0.522, 0.157, 30.3], info: [0.515, 0.064, 232.1] },
  dark: { success: [0.72, 0.078, 135.6], warning: [0.792, 0.118, 82.9], danger: [0.712, 0.116, 36.5], info: [0.728, 0.057, 220.1] },
} as const;

/** sRGB hex — legacy fallback only; the OKLCH components above are authoritative. */
export const roleHex = {
  light: { primary: '#B0512E', onPrimary: '#FFFFFF', primaryHover: '#9C4728', primaryActive: '#883E22', link: '#8E4126', primarySoft: '#F6E1D4', primaryWash: '#FCF1EA', text: '#271F1A', textSecondary: '#6B6055', textTertiary: '#776B56', bgLayout: '#F3EEE4', bgContainer: '#FDFBF5', bgElevated: '#F7F2E8', bgSunken: '#EAE2D3', border: '#E5DDCD', borderSecondary: '#EFE8DA', focus: '#8E4126' },
  dark: { primary: '#EA9468', onPrimary: '#2A1610', primaryHover: '#E08A5C', primaryActive: '#D17E50', link: '#EE9C71', primarySoft: '#36231A', primaryWash: '#281A12', text: '#EFE6DB', textSecondary: '#B0A597', textTertiary: '#8F8576', bgLayout: '#1A1512', bgContainer: '#221B16', bgElevated: '#1E1813', bgSunken: '#120E0B', border: '#3A322B', borderSecondary: '#2C2620', focus: '#EE9C71' },
} as const;

export const yarnHex = {
  light: { brick: '#B0512E', teal: '#3F6E86', ochre: '#C7973C', fern: '#5F8B55', clay: '#C0664A', plum: '#7A5A86' },
  dark: { brick: '#EA9468', teal: '#7FB0C0', ochre: '#E0B45C', fern: '#8FB07F', clay: '#D98A6F', plum: '#B394C0' },
} as const;

export const semanticHex = {
  light: { success: '#5F8B55', warning: '#C7973C', danger: '#B23B2C', info: '#3F6E86' },
  dark: { success: '#8FB07F', warning: '#E0B45C', danger: '#E0876E', info: '#7FB0C0' },
} as const;
