/* GENERATED by scripts/build-tokens.ts from src/tokens/tokens.json — do not edit. */

import type { OKLCH } from './palette';

export type { OKLCH };

export const radii = { sm: 6, base: 8, lg: 10, xl: 16 } as const;

export const sizing = {
	controlHeight: 40,
	fontSize: 14,
	containerMaxWidth: 1120,
} as const;

/** 8-px rhythm; the number IS the pixel size. Use these keys, never raw px. */
export const space = {
	0: 0,
	2: 2,
	4: 4,
	8: 8,
	12: 12,
	16: 16,
	20: 20,
	24: 24,
	32: 32,
	40: 40,
	48: 48,
	64: 64,
	80: 80,
	96: 96,
} as const;

export const size = {
	icon: { sm: 16, md: 20, lg: 24 },
	control: { sm: 32, md: 40, lg: 48 },
	touchMin: 44,
	sidebar: 264,
	container: 1120,
} as const;

export const fonts = {
	body: 'Inter, system-ui, -apple-system, "Segoe UI", Roboto, Arial, sans-serif',
	display:
		'"Space Grotesk", Inter, system-ui, -apple-system, "Segoe UI", Roboto, Arial, sans-serif',
} as const;

export const shadows = {
	soft: '0 1px 2px rgba(40,30,20,.06), 0 6px 20px rgba(40,30,20,.06)',
	softer: '0 1px 2px rgba(40,30,20,.08)',
	lifted: '0 2px 4px rgba(40,30,20,.06), 0 12px 32px rgba(40,30,20,.10)',
} as const;

/** Semantic role tokens as OKLCH strings — light + dark. Pass straight to AntD or CSS. */
export const tokens = {
	light: {
		primary: 'oklch(54.9% 0.134 40.1)',
		onPrimary: 'oklch(100.0% 0.000 0.0)',
		primaryHover: 'oklch(50.2% 0.122 39.9)',
		primaryActive: 'oklch(45.6% 0.109 40.5)',
		link: 'oklch(47.1% 0.112 39.4)',
		primarySoft: 'oklch(92.3% 0.029 54.0)',
		primaryWash: 'oklch(96.5% 0.015 54.9)',
		text: 'oklch(24.7% 0.016 53.8)',
		textSecondary: 'oklch(49.6% 0.022 67.3)',
		textTertiary: 'oklch(53.3% 0.035 81.6)',
		bgLayout: 'oklch(95.0% 0.014 84.6)',
		bgContainer: 'oklch(98.8% 0.008 91.5)',
		bgElevated: 'oklch(96.2% 0.014 84.6)',
		bgSunken: 'oklch(91.5% 0.022 83.3)',
		border: 'oklch(90.0% 0.023 84.6)',
		borderSecondary: 'oklch(93.3% 0.020 84.6)',
		focus: 'oklch(47.1% 0.112 39.4)',
		yarn: {
			brick: 'oklch(54.9% 0.134 40.1)',
			teal: 'oklch(51.5% 0.064 232.1)',
			ochre: 'oklch(70.5% 0.121 80.3)',
			fern: 'oklch(59.0% 0.093 139.9)',
			clay: 'oklch(60.9% 0.123 38.0)',
			plum: 'oklch(51.7% 0.077 316.6)',
		},
		semantic: {
			success: 'oklch(59.0% 0.093 139.9)',
			warning: 'oklch(70.5% 0.121 80.3)',
			danger: 'oklch(52.2% 0.157 30.3)',
			info: 'oklch(51.5% 0.064 232.1)',
		},
	},
	dark: {
		primary: 'oklch(74.5% 0.120 47.4)',
		onPrimary: 'oklch(22.6% 0.035 37.5)',
		primaryHover: 'oklch(71.4% 0.122 48.2)',
		primaryActive: 'oklch(67.3% 0.120 48.8)',
		link: 'oklch(76.5% 0.114 48.1)',
		primarySoft: 'oklch(27.7% 0.033 46.2)',
		primaryWash: 'oklch(23.3% 0.027 50.7)',
		text: 'oklch(92.9% 0.018 73.1)',
		textSecondary: 'oklch(72.7% 0.024 74.0)',
		textTertiary: 'oklch(62.1% 0.025 78.1)',
		bgLayout: 'oklch(20.1% 0.010 52.9)',
		bgContainer: 'oklch(22.9% 0.015 57.5)',
		bgElevated: 'oklch(21.4% 0.014 61.8)',
		bgSunken: 'oklch(16.8% 0.009 59.0)',
		border: 'oklch(32.3% 0.017 63.4)',
		borderSecondary: 'oklch(27.3% 0.014 67.2)',
		focus: 'oklch(76.5% 0.114 48.1)',
		yarn: {
			brick: 'oklch(74.5% 0.120 47.4)',
			teal: 'oklch(72.8% 0.057 220.1)',
			ochre: 'oklch(79.2% 0.118 82.9)',
			fern: 'oklch(72.0% 0.078 135.6)',
			clay: 'oklch(70.9% 0.105 39.6)',
			plum: 'oklch(70.9% 0.072 315.8)',
		},
		semantic: {
			success: 'oklch(72.0% 0.078 135.6)',
			warning: 'oklch(79.2% 0.118 82.9)',
			danger: 'oklch(71.2% 0.116 36.5)',
			info: 'oklch(72.8% 0.057 220.1)',
		},
	},
} as const;

export type ColorTokens = typeof tokens.light;
export type ThemeMode = keyof typeof tokens;
export type SpaceKey = keyof typeof space;
export type RadiusKey = keyof typeof radii;
