/**
 * build-tokens.ts — codegen. Reads the DTCG source `src/tokens/tokens.json` and
 * emits every token artifact (agent-first: one machine-readable source, generate the rest).
 *
 *   src/tokens/palette.ts  — OKLCH [L,C,H] components + helpers + sRGB hex fallback (for CI)
 *   src/tokens/tokens.ts   — semantic role tokens (oklch() strings) + space/size/radius/font/shadow scales
 *   src/tokens/tokens.css  — :root (light) + [data-theme="dark"] + focus ring + reduced-motion guard
 *   figma/FOUNDATIONS.md   — token ↔ hex tables for building the Figma variable library
 *   docs/foundations.md    — human-readable token reference (hex + OKLCH)
 *
 * Run: `npm run build:tokens` (also runs automatically as `prebuild`). Never hand-edit the outputs.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

type Triple = [number, number, number];
type Mode = 'light' | 'dark';
// biome-ignore lint/suspicious/noExplicitAny: token JSON is a loosely-typed DTCG tree parsed at build time.
type Tok = Record<string, any>;

const ROOT = process.cwd();
const P = (...p: string[]) => join(ROOT, ...p);
const dt: Tok = JSON.parse(readFileSync(P('src/tokens/tokens.json'), 'utf8'));

const TW = 'com.threadwick';
const tw = (t: Tok) => (t.$extensions?.[TW] ?? {}) as Tok;
const isTok = (k: string) => !k.startsWith('$');
const entries = (group: Tok): [string, Tok][] =>
	Object.entries(group).filter(([k]) => isTok(k));

const triple = (t: Tok, m: Mode): Triple =>
	m === 'dark' ? (tw(t).dark?.oklch ?? tw(t).oklch) : tw(t).oklch;
const hex = (t: Tok, m: Mode): string =>
	m === 'dark' ? (tw(t).dark?.value ?? t.$value) : t.$value;

const fmt = ([l, c, h]: Triple): string =>
	`oklch(${(l * 100).toFixed(1)}% ${c.toFixed(3)} ${h.toFixed(1)})`;
const px = (t: Tok): number => parseFloat(t.$value);
const kebab = (s: string) =>
	s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const fontCss = (fams: string[]) =>
	fams.map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(', ');
const HEADER =
	'/* GENERATED by scripts/build-tokens.ts from src/tokens/tokens.json — do not edit. */\n';
const CSS_HEADER =
	'/* GENERATED by scripts/build-tokens.ts from src/tokens/tokens.json — do not edit. */\n';

const roles = entries(dt.color.role);
const yarns = entries(dt.color.yarn);
const sems = entries(dt.color.semantic);
const radius = dt.radius;
const sizing = dt.sizing;
const sz = dt.size;

// ── palette.ts ───────────────────────────────────────────────────────────────
const tripleMap = (list: [string, Tok][], m: Mode) =>
	'{ ' +
	list.map(([k, t]) => `${k}: [${triple(t, m).join(', ')}]`).join(', ') +
	' }';
const hexMap = (list: [string, Tok][], m: Mode) =>
	`{ ${list.map(([k, t]) => `${k}: '${hex(t, m)}'`).join(', ')} }`;

writeFileSync(
	P('src/tokens/palette.ts'),
	HEADER +
		`
export type OKLCH = readonly [number, number, number]; // [L 0..1, C, H°]

/** Format OKLCH components as a CSS \`oklch()\` string. */
export const oklch = ([l, c, h]: OKLCH, a = 1): string =>
  \`oklch(\${(l * 100).toFixed(1)}% \${c.toFixed(3)} \${h.toFixed(1)}\${a === 1 ? '' : \` / \${a}\`})\`;

/** Nudge perceptual lightness, clamped to [0,1] — derive hover/active/soft states on one hue. */
export const L = ([l, c, h]: OKLCH, d: number): OKLCH => [Math.min(1, Math.max(0, l + d)), c, h];

/** Authoritative OKLCH components — store as [L,C,H] so CI can re-check contrast + gamut. */
export const roleOklch = {
  light: ${tripleMap(roles, 'light')},
  dark: ${tripleMap(roles, 'dark')},
} as const;

export const yarnOklch = {
  light: ${tripleMap(yarns, 'light')},
  dark: ${tripleMap(yarns, 'dark')},
} as const;

export const semanticOklch = {
  light: ${tripleMap(sems, 'light')},
  dark: ${tripleMap(sems, 'dark')},
} as const;

/** sRGB hex — legacy fallback only; the OKLCH components above are authoritative. */
export const roleHex = {
  light: ${hexMap(roles, 'light')},
  dark: ${hexMap(roles, 'dark')},
} as const;

export const yarnHex = {
  light: ${hexMap(yarns, 'light')},
  dark: ${hexMap(yarns, 'dark')},
} as const;

export const semanticHex = {
  light: ${hexMap(sems, 'light')},
  dark: ${hexMap(sems, 'dark')},
} as const;
`,
);

// ── tokens.ts ────────────────────────────────────────────────────────────────
const roleStrings = (m: Mode) =>
	roles.map(([k, t]) => `    ${k}: '${fmt(triple(t, m))}'`).join(',\n');
const groupStrings = (list: [string, Tok][], m: Mode) =>
	list.map(([k, t]) => `${k}: '${fmt(triple(t, m))}'`).join(', ');
const spaceObj = entries(dt.space)
	.map(([k, t]) => `${k}: ${px(t)}`)
	.join(', ');

writeFileSync(
	P('src/tokens/tokens.ts'),
	HEADER +
		`
import type { OKLCH } from './palette';
export type { OKLCH };

export const radii = { sm: ${px(radius.sm)}, base: ${px(radius.base)}, lg: ${px(radius.lg)}, xl: ${px(radius.xl)} } as const;

export const sizing = { controlHeight: ${px(sizing.controlHeight)}, fontSize: ${px(sizing.fontSize)}, containerMaxWidth: ${px(sz.container)} } as const;

/** 8-px rhythm; the number IS the pixel size. Use these keys, never raw px. */
export const space = { ${spaceObj} } as const;

export const size = {
  icon: { sm: ${px(sz.iconSm)}, md: ${px(sz.iconMd)}, lg: ${px(sz.iconLg)} },
  control: { sm: ${px(sz.controlSm)}, md: ${px(sz.controlMd)}, lg: ${px(sz.controlLg)} },
  touchMin: ${px(sz.touchMin)},
  sidebar: ${px(sz.sidebar)},
  container: ${px(sz.container)},
} as const;

export const fonts = {
  body: '${fontCss(dt.font.body.$value)}',
  display: '${fontCss(dt.font.display.$value)}',
} as const;

export const shadows = {
  soft: '${dt.shadow.soft.$value}',
  softer: '${dt.shadow.softer.$value}',
  lifted: '${dt.shadow.lifted.$value}',
} as const;

/** Semantic role tokens as OKLCH strings — light + dark. Pass straight to AntD or CSS. */
export const tokens = {
  light: {
${roleStrings('light')},
    yarn: { ${groupStrings(yarns, 'light')} },
    semantic: { ${groupStrings(sems, 'light')} },
  },
  dark: {
${roleStrings('dark')},
    yarn: { ${groupStrings(yarns, 'dark')} },
    semantic: { ${groupStrings(sems, 'dark')} },
  },
} as const;

export type ColorTokens = typeof tokens.light;
export type ThemeMode = keyof typeof tokens;
export type SpaceKey = keyof typeof space;
export type RadiusKey = keyof typeof radii;
`,
);

// ── tokens.css ───────────────────────────────────────────────────────────────
const roleVars = (m: Mode) =>
	roles.map(([k, t]) => `  --tw-${kebab(k)}: ${fmt(triple(t, m))};`).join('\n');
const yarnVars = (m: Mode) =>
	yarns.map(([k, t]) => `  --tw-yarn-${k}: ${fmt(triple(t, m))};`).join('\n');
const semVars = (m: Mode) =>
	sems.map(([k, t]) => `  --tw-${k}: ${fmt(triple(t, m))};`).join('\n');
const scaleVars = [
	...entries(dt.space).map(([k, t]) => `  --tw-space-${k}: ${px(t)}px;`),
	`  --tw-control: ${px(sz.controlMd)}px;`,
	`  --tw-control-sm: ${px(sz.controlSm)}px;`,
	`  --tw-control-lg: ${px(sz.controlLg)}px;`,
	`  --tw-radius-sm: ${px(radius.sm)}px;`,
	`  --tw-radius: ${px(radius.base)}px;`,
	`  --tw-radius-lg: ${px(radius.lg)}px;`,
	`  --tw-radius-xl: ${px(radius.xl)}px;`,
	`  --tw-font-body: ${fontCss(dt.font.body.$value)};`,
	`  --tw-font-display: ${fontCss(dt.font.display.$value)};`,
].join('\n');

writeFileSync(
	P('src/tokens/tokens.css'),
	CSS_HEADER +
		`:root {
${roleVars('light')}
${yarnVars('light')}
${semVars('light')}

  /* scales — mode-independent */
${scaleVars}
}

[data-theme='dark'] {
${roleVars('dark')}
${yarnVars('dark')}
${semVars('dark')}
}

/* Accessibility baked into the system (WCAG 2.1 AA). Consumers inherit these by default. */
:focus-visible {
  outline: 2px solid var(--tw-focus);
  outline-offset: 2px;
}

@media (prefers-reduced-motion: reduce) {
  *,
  *::before,
  *::after {
    animation-duration: 0.001ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.001ms !important;
    scroll-behavior: auto !important;
  }
}
`,
);

// ── foundations markdown (Figma library + human reference) ──────────────────────
const table = (list: [string, Tok][], withOklch: boolean) => {
	const head = withOklch
		? '| Token | Light hex | Dark hex | Light OKLCH | Dark OKLCH |\n|---|---|---|---|---|'
		: '| Token | Light hex | Dark hex |\n|---|---|---|';
	const rows = list.map(([k, t]) =>
		withOklch
			? `| \`${k}\` | \`${hex(t, 'light')}\` | \`${hex(t, 'dark')}\` | \`${fmt(triple(t, 'light'))}\` | \`${fmt(triple(t, 'dark'))}\` |`
			: `| \`${k}\` | \`${hex(t, 'light')}\` | \`${hex(t, 'dark')}\` |`,
	);
	return [head, ...rows].join('\n');
};

const foundations = (withOklch: boolean) =>
	`<!-- GENERATED by scripts/build-tokens.ts from src/tokens/tokens.json — do not edit. -->
# Brick & Ecru — token foundations

Generated from \`src/tokens/tokens.json\`. OKLCH is authoritative; hex is the legacy sRGB fallback.

## Role tokens
${table(roles, withOklch)}

## Yarn / craft palette
${table(yarns, withOklch)}

## Semantic states
${table(sems, withOklch)}

## Scales (mode-independent)
- **Space:** ${entries(dt.space)
		.map(([k]) => k)
		.join(' · ')} (px)
- **Radius:** sm ${px(radius.sm)} · base ${px(radius.base)} · lg ${px(radius.lg)} · xl ${px(radius.xl)} (px)
- **Control:** sm ${px(sz.controlSm)} · md ${px(sz.controlMd)} · lg ${px(sz.controlLg)} · touch-min ${px(sz.touchMin)} (px)
- **Font:** body \`${fontCss(dt.font.body.$value)}\`; display \`${fontCss(dt.font.display.$value)}\`
`;

writeFileSync(P('figma/FOUNDATIONS.md'), foundations(false));
writeFileSync(P('docs/foundations.md'), foundations(true));

// ── figma/variables.json — importable Figma variable definitions (one collection, 2 modes) ──
const colorVars = (group: Tok, prefix: string) =>
	entries(group).map(([k, t]) => ({
		name: `${prefix}/${k}`,
		type: 'color',
		valuesByMode: { light: hex(t, 'light'), dark: hex(t, 'dark') },
	}));
const floatVars = (group: Tok, prefix: string) =>
	entries(group).map(([k, t]) => ({
		name: `${prefix}/${k}`,
		type: 'float',
		valuesByMode: { light: px(t), dark: px(t) }, // mode-independent scales: same in both modes
	}));
const figmaVars = {
	$description:
		'GENERATED by scripts/build-tokens.ts — Figma variable definitions for the Brick & Ecru collection (light + dark modes). Import via a Figma variables / Tokens-Studio plugin.',
	collection: 'Brick & Ecru',
	modes: ['light', 'dark'],
	variables: [
		...colorVars(dt.color.role, 'color/role'),
		...colorVars(dt.color.yarn, 'color/yarn'),
		...colorVars(dt.color.semantic, 'color/semantic'),
		...floatVars(dt.space, 'space'),
		...floatVars(dt.radius, 'radius'),
	],
};
writeFileSync(
	P('figma/variables.json'),
	`${JSON.stringify(figmaVars, null, 2)}\n`,
);

const n = roles.length + yarns.length + sems.length;
console.log(
	`build-tokens: emitted palette.ts, tokens.ts, tokens.css, figma/variables.json, 2× foundations.md (${n} colour tokens).`,
);
