/**
 * Brand-glyph generator — a UTILITY. It must never run during a build.
 *
 * Brand marks are fixed identity assets, so their geometry is baked into
 * `src/brand/glyphs.ts` as static `{ path, viewBox }` and committed — the product build
 * then needs no Font Awesome Pro token. Run this only to change a logo glyph, then commit
 * the regenerated `glyphs.ts`.
 *
 * Font Awesome Pro is an OPTIONAL dependency. To enable it locally:
 *   1. In a local `.npmrc` (never commit your token):
 *        @fortawesome:registry=https://npm.fontawesome.com/
 *        //npm.fontawesome.com/:_authToken=${FONTAWESOME_NPM_AUTH_TOKEN}
 *   2. `export FONTAWESOME_NPM_AUTH_TOKEN=… && pnpm install`
 *   3. `pnpm --filter @threadwick/core gen:brand-glyphs`
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

type FaIconDefinition = {
	icon: [number, number, unknown, unknown, string | string[]];
};

type GlyphSpec = {
	/** The exported constant name in `glyphs.ts`. */
	constName: string;
	/** Doc comment for the generated constant. */
	doc: string;
	/** The Font Awesome Pro Regular export to read (e.g. `faReel`). */
	faName: string;
};

/** Each brand mark and the Font Awesome Pro Regular glyph it renders. Add surfaces here. */
const GLYPH_SPECS: GlyphSpec[] = [
	{ constName: 'REEL', doc: 'Threadwick — a reel.', faName: 'faReel' },
	{ constName: 'COMPASS_DRAFTING', doc: 'Threadwick Studio — a drafting compass.', faName: 'faCompassDrafting' },
	{ constName: 'STORE', doc: 'Threadwick Marketplace — a storefront.', faName: 'faStore' },
];

const OUTPUT = fileURLToPath(new URL('../src/brand/glyphs.ts', import.meta.url));

async function generate(): Promise<void> {
	const pro = await loadFontAwesomePro();
	const blocks = GLYPH_SPECS.map((spec) => {
		const faIcon = pro[spec.faName];
		if (faIcon === undefined) {
			throw new Error(`Glyph '${spec.faName}' was not found in Font Awesome Pro Regular.`);
		}
		const [width, height, , , data] = faIcon.icon;
		const path = Array.isArray(data) ? data.join('') : data;
		return `/** ${spec.doc} */\nexport const ${spec.constName}: IconGlyph = {\n\tviewBox: '0 0 ${width} ${height}',\n\tpath: '${path}',\n};`;
	});

	const header =
		`import type { IconGlyph } from './Logo';\n\n` +
		`// GENERATED by scripts/gen-brand-glyphs.ts from Font Awesome Pro — do not edit by hand.\n` +
		`// Brand marks are fixed identity assets, so their geometry is committed here and the\n` +
		`// product build needs no Font Awesome Pro token. Re-run the generator to change a glyph.\n\n`;

	writeFileSync(OUTPUT, `${header}${blocks.join('\n\n')}\n`);
	console.log(`Wrote ${OUTPUT} (${GLYPH_SPECS.length} glyphs).`);
}

/** Dynamically load the optional Font Awesome Pro package, narrowed to the shape we read. */
async function loadFontAwesomePro(): Promise<Record<string, FaIconDefinition | undefined>> {
	// A non-literal specifier keeps tsc from resolving (and failing on) the optional package.
	const moduleId: string = '@fortawesome/pro-regular-svg-icons';
	try {
		const pro: Record<string, FaIconDefinition | undefined> = await import(moduleId);
		return pro;
	} catch {
		throw new Error(
			"Font Awesome Pro is not installed. Configure the FA registry + FONTAWESOME_NPM_AUTH_TOKEN and run pnpm install (see this file's header).",
		);
	}
}

generate().catch((error: unknown) => {
	console.error(error instanceof Error ? error.message : error);
	process.exit(1);
});
