import { join } from 'node:path';
import type { Locale } from '../src/locale';
import { LOCALES, TARGET_LOCALES } from '../src/locale';
import type { Messages, SourceEntry } from '../src/schema';
import { loadOverrides, loadSource, loadTranslations } from './catalog';
import { writeJson, writeText } from './io';
import { PATHS } from './paths';

const HEADER = '// GENERATED by scripts/codegen.ts. Do not edit by hand.';

// codegen

function main(): void {
	const source = loadSource();
	const namespaces = Object.keys(source).sort();

	writeSourceMessages(source);
	writeTargetMessages(source);
	writeText(join(PATHS.generated, 'keys.ts'), renderKeys(source, namespaces));
	writeText(join(PATHS.generated, 'bundles.ts'), renderBundles(namespaces));

	console.log(
		`i18n codegen: ${namespaces.length} namespace(s) x ${LOCALES.length} locale(s).`,
	);
}

/** Writes the English runtime bundles straight from the source text. */
function writeSourceMessages(
	source: Record<string, Record<string, SourceEntry>>,
): void {
	for (const [namespace, entries] of Object.entries(source)) {
		const messages: Messages = {};
		for (const [key, entry] of Object.entries(entries)) {
			messages[key] = entry.text;
		}
		writeJson(join(PATHS.messages, 'en', `${namespace}.json`), messages);
	}
}

/** Writes each target bundle as override, else translation, else the English fallback. */
function writeTargetMessages(
	source: Record<string, Record<string, SourceEntry>>,
): void {
	for (const locale of TARGET_LOCALES) {
		const translations = loadTranslations(locale);
		const overrides = loadOverrides(locale);
		for (const [namespace, entries] of Object.entries(source)) {
			const messages: Messages = {};
			for (const [key, entry] of Object.entries(entries)) {
				const override = overrides[namespace]?.[key];
				const translated = translations[namespace]?.[key]?.value;
				messages[key] = override ?? translated ?? entry.text;
			}
			writeJson(join(PATHS.messages, locale, `${namespace}.json`), messages);
		}
	}
}

/** Renders the typed key surface: one key union per namespace, plus the namespaced MessageKey. */
function renderKeys(
	source: Record<string, Record<string, SourceEntry>>,
	namespaces: string[],
): string {
	const keyTypes = namespaces.map((namespace) => {
		const keys = Object.keys(source[namespace] ?? {});
		const union = keys.length === 0 ? 'never' : keys.map(quote).join(' | ');
		return `export type ${keyType(namespace)} = ${union};`;
	});

	const messageKey = namespaces
		.map((namespace) => `\`${namespace}.\${${keyType(namespace)}}\``)
		.join(' | ');

	const keyTable = namespaces
		.map((namespace) => {
			const keys = Object.keys(source[namespace] ?? {});
			const items = keys.map((key) => `\t\t${quote(key)},`).join('\n');
			return `\t${namespace}: [\n${items}\n\t],`;
		})
		.join('\n');

	return [
		HEADER,
		'',
		keyTypes.join('\n'),
		'',
		`export type MessageKey = ${messageKey || 'never'};`,
		'',
		`export const MESSAGE_KEYS = {\n${keyTable}\n} as const;`,
	].join('\n');
}

/** Renders the bundle loader that statically imports every committed message file. */
function renderBundles(namespaces: string[]): string {
	const imports: string[] = [];
	const entries: string[] = [];
	for (const locale of LOCALES) {
		const localeEntries = namespaces
			.map((namespace) => {
				const name = bundleVar(locale, namespace);
				imports.push(
					`import ${name} from '../../messages/${locale}/${namespace}.json';`,
				);
				return `\t\t${namespace}: ${name},`;
			})
			.join('\n');
		entries.push(`\t${locale}: {\n${localeEntries}\n\t},`);
	}

	return [
		HEADER,
		'',
		"import type { Locale, Namespace } from '../locale';",
		"import type { Messages } from '../schema';",
		imports.join('\n'),
		'',
		`const BUNDLES: Record<Locale, Partial<Record<Namespace, Messages>>> = {\n${entries.join('\n')}\n};`,
		'',
		'const EMPTY: Messages = {};',
		'',
		'/** Returns the context-stripped bundle for a locale and namespace, or an empty bundle. */',
		'function getMessages(locale: Locale, namespace: Namespace): Messages {',
		'\treturn BUNDLES[locale]?.[namespace] ?? EMPTY;',
		'}',
		'',
		'export { BUNDLES, getMessages };',
	].join('\n');
}

// helpers

function keyType(namespace: string): string {
	return `${capitalize(namespace)}Key`;
}

function bundleVar(locale: Locale, namespace: string): string {
	return `${locale}${capitalize(namespace)}`;
}

function capitalize(value: string): string {
	return value.charAt(0).toUpperCase() + value.slice(1);
}

function quote(value: string): string {
	return `'${value}'`;
}

main();
