import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/tokens/index.ts',
    'src/theme/index.ts',
    'src/brand/index.ts',
    'src/components/index.ts',
    'src/lib/utils.ts',
  ],
  format: ['esm'],
  dts: true,
  clean: true,
  treeshake: true,
  external: ['react', 'antd', '@threadwick/icons', /@radix-ui\//],
  // Bundle the Font Awesome Pro icon data into dist so consumers don't need a FA token.
  noExternal: [/@fortawesome\//],
  // tokens.css is generated by build-tokens.ts (prebuild); ship it as a side-effect entry.
  onSuccess: 'cp src/tokens/tokens.css dist/tokens.css && cp src/styles/theme.css dist/theme.css',
});
