import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import { faGoogle } from '@fortawesome/free-brands-svg-icons';
import {
	faArrowLeft,
	faArrowPointer,
	faArrowRight,
	faArrowsRotate,
	faArrowUpRightFromSquare,
	faArrowUpWideShort,
	faBars,
	faBell,
	faBookOpen,
	faCheck,
	faChevronDown,
	faChevronUp,
	faCirclePlus,
	faCircleQuestion,
	faCircleUser,
	faClone,
	faCloudArrowUp,
	faCode,
	faCodeBranch,
	faCompass,
	faCopy,
	faCrosshairs,
	faDownload,
	faDroplet,
	faEllipsisVertical,
	faEnvelope,
	faEraser,
	faExpand,
	faEye,
	faFileExport,
	faFilePdf,
	faFilePen,
	faFilter,
	faFingerprint,
	faFolder,
	faFolderOpen,
	faGear,
	faGift,
	faHand,
	faHandHoldingDollar,
	faHeart,
	faHouse,
	faKey,
	faLaptop,
	faLink,
	faLock,
	faLockOpen,
	faMagnifyingGlass,
	faMagnifyingGlassMinus,
	faMagnifyingGlassPlus,
	faNoteSticky,
	faPalette,
	faPenNib,
	faPenRuler,
	faPenToSquare,
	faPlay,
	faPlus,
	faQrcode,
	faRightFromBracket,
	faRightLeft,
	faRightToBracket,
	faRotateLeft,
	faRotateRight,
	faScrewdriverWrench,
	faSliders,
	faStar,
	faStore,
	faTableCells,
	faTrash,
	faUpload,
	faUsers,
	faXmark,
} from '@fortawesome/free-solid-svg-icons';
import type { IconName, IconSet } from '../contract';

/** The only place glyph names appear — the Font Awesome Free mapping of each action. */
const glyphs: Record<IconName, IconDefinition> = {
	close: faXmark,
	search: faMagnifyingGlass,
	'open-menu': faBars,
	settings: faGear,
	'open-external': faArrowUpRightFromSquare,
	expand: faChevronDown,
	collapse: faChevronUp,
	copy: faCopy,
	download: faDownload,
	confirm: faCheck,
	add: faPlus,
	delete: faTrash,
	edit: faPenToSquare,
	next: faArrowRight,
	previous: faArrowLeft,
	private: faLock,
	'publish-pattern': faCloudArrowUp,
	'open-in-studio': faPenRuler,
	'make-it': faPlay,
	'export-chart': faFileExport,
	'remix-pattern': faCodeBranch,
	'rotate-stitch-right': faRotateRight,
	'rotate-stitch-left': faRotateLeft,
	'mirror-stitch': faRightLeft,
	'add-round': faCirclePlus,
	'delete-stitch': faEraser,
	'set-stitch-color': faPalette,
	'set-origin': faCrosshairs,
	undo: faRotateLeft,
	redo: faRotateRight,
	'zoom-in': faMagnifyingGlassPlus,
	'zoom-out': faMagnifyingGlassMinus,
	fit: faExpand,
	'select-mode': faArrowPointer,
	'insert-mode': faCirclePlus,
	'pan-mode': faHand,
	import: faUpload,
	more: faEllipsisVertical,
	'chevron-down': faChevronDown,
	help: faCircleQuestion,
	yarn: faDroplet,
	notes: faNoteSticky,
	variation: faClone,
	'sign-in': faRightToBracket,
	'sign-out': faRightFromBracket,
	account: faCircleUser,
	google: faGoogle,
	mail: faEnvelope,
	organize: faFolderOpen,
	draft: faFilePen,
	'share-qr': faQrcode,
	sync: faCloudArrowUp,
	symbols: faPenNib,
	community: faUsers,
	gift: faGift,
	earnings: faHandHoldingDollar,
	'no-lock-in': faLockOpen,
	refresh: faArrowsRotate,
	devices: faLaptop,
	marketplace: faStore,
	'license-key': faKey,
	fingerprint: faFingerprint,
	api: faCode,
	preview: faEye,
	pdf: faFilePdf,
	link: faLink,
	view: faBookOpen,
	customize: faSliders,
	home: faHouse,
	patterns: faTableCells,
	projects: faFolder,
	tools: faScrewdriverWrench,
	browse: faCompass,
	wishlist: faHeart,
	bell: faBell,
	star: faStar,
	sort: faArrowUpWideShort,
	filter: faFilter,
};

export const faFree: IconSet = {
	id: 'fa-free',
	resolve: (name) => glyphs[name],
};
