import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
	faArrowLeft,
	faArrowRight,
	faArrowUpRightFromSquare,
	faBars,
	faCheck,
	faChevronDown,
	faChevronUp,
	faCirclePlus,
	faCloudArrowUp,
	faCodeBranch,
	faCopy,
	faDownload,
	faEraser,
	faFileExport,
	faGear,
	faMagnifyingGlass,
	faMagnifyingGlassMinus,
	faMagnifyingGlassPlus,
	faPalette,
	faPenRuler,
	faPenToSquare,
	faPlay,
	faPlus,
	faRightLeft,
	faRotateLeft,
	faRotateRight,
	faTrash,
	faXmark,
} from '@fortawesome/free-solid-svg-icons';
import type { IconName, IconSet } from '../contract';

/** The only place glyph names appear — the Font Awesome Free mapping of each action. */
const glyphs: Record<IconName, IconDefinition> = {
	close: faXmark,
	search: faMagnifyingGlass,
	'open-menu': faBars,
	settings: faGear,
	'open-external': faArrowUpRightFromSquare,
	expand: faChevronDown,
	collapse: faChevronUp,
	copy: faCopy,
	download: faDownload,
	confirm: faCheck,
	add: faPlus,
	delete: faTrash,
	edit: faPenToSquare,
	next: faArrowRight,
	previous: faArrowLeft,
	'publish-pattern': faCloudArrowUp,
	'open-in-studio': faPenRuler,
	'make-it': faPlay,
	'export-chart': faFileExport,
	'remix-pattern': faCodeBranch,
	'rotate-stitch-right': faRotateRight,
	'rotate-stitch-left': faRotateLeft,
	'mirror-stitch': faRightLeft,
	'add-round': faCirclePlus,
	'delete-stitch': faEraser,
	'set-stitch-color': faPalette,
	undo: faRotateLeft,
	redo: faRotateRight,
	'zoom-in': faMagnifyingGlassPlus,
	'zoom-out': faMagnifyingGlassMinus,
};

export const faFree: IconSet = {
	id: 'fa-free',
	resolve: (name) => glyphs[name],
};
